/** @type {import('eslint').Linter.Config} */
export default [
  {
    ignores: [
      '**/*',
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/build/**'
    ]
  },
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    rules: {
      // Disable all rules
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@next/next/no-img-element': 'off',
      'no-unused-vars': 'off',
      'no-console': 'off',
      'prefer-const': 'off',
      'no-var': 'off',
      'no-undef': 'off',
      'no-redeclare': 'off',
      'no-duplicate-imports': 'off',
      'no-unreachable': 'off',
      'no-constant-condition': 'off',
      'no-empty': 'off',
      'no-extra-semi': 'off',
      'no-irregular-whitespace': 'off',
      'no-mixed-spaces-and-tabs': 'off',
      'no-trailing-spaces': 'off',
      'no-unexpected-multiline': 'off',
      'no-unreachable': 'off',
      'no-unsafe-finally': 'off',
      'no-unsafe-negation': 'off',
      'use-isnan': 'off',
      'valid-typeof': 'off',
      'curly': 'off',
      'eqeqeq': 'off',
      'no-alert': 'off',
      'no-caller': 'off',
      'no-eval': 'off',
      'no-extend-native': 'off',
      'no-extra-bind': 'off',
      'no-fallthrough': 'off',
      'no-floating-decimal': 'off',
      'no-implied-eval': 'off',
      'no-lone-blocks': 'off',
      'no-loop-func': 'off',
      'no-multi-spaces': 'off',
      'no-multi-str': 'off',
      'no-new': 'off',
      'no-new-func': 'off',
      'no-new-wrappers': 'off',
      'no-octal': 'off',
      'no-octal-escape': 'off',
      'no-param-reassign': 'off',
      'no-proto': 'off',
      'no-return-assign': 'off',
      'no-script-url': 'off',
      'no-self-compare': 'off',
      'no-sequences': 'off',
      'no-throw-literal': 'off',
      'no-with': 'off',
      'radix': 'off',
      'vars-on-top': 'off',
      'wrap-iife': 'off',
      'yoda': 'off'
    }
  }
];